apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-stock-pulse-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/OmriHalpert/ai-stock-pulse-manifests.git
    targetRevision: main
    path: charts/ai-stock-pulse
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true