global:
  environment: dev

backend:
  replicaCount: 1
  image:
    repository: 661985535801.dkr.ecr.eu-west-1.amazonaws.com/ai-stock-pulse/backend
    tag: "64fd812"
frontend:
  replicaCount: 1
  image:
    repository: 661985535801.dkr.ecr.eu-west-1.amazonaws.com/ai-stock-pulse/frontend
    tag: "64fd812"
agent:
  replicaCount: 1
  image:
    repository: 661985535801.dkr.ecr.eu-west-1.amazonaws.com/ai-stock-pulse/agent
    tag: "64fd812"
  env:
    marketDataProvider: finnhub
postgres:
  enabled: false

ingress:
  enabled: true
  className: alb
  host: app.ai-stuck-pulse.xyz
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:661985535801:certificate/87f1910a-5152-4d5f-be36-b3b58317533f
    alb.ingress.kubernetes.io/group.name: ai-stock-pulse

secrets:
  existingSecret: stock-pulse-secrets