global:
  environment: dev

backend:
  replicaCount: 0
  image:
    tag: "3e286fe"
frontend:
  replicaCount: 1
  image:
    tag: "3e286fe"
agent:
  replicaCount: 1
  image:
    tag: "3e286fe"
  env:
    marketDataProvider: finnhub

ingress:
  enabled: true
  className: ""
  host: ""

secrets:
  existingSecret: stock-pulse-secrets
