apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ai-stock-pulse.fullname" . }}-external-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-stock-pulse.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: stock-pulse-secretstore
    kind: SecretStore
  target:
    name: {{ include "ai-stock-pulse.secretName" . }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "{{ `{{ .username }}` }}"
        POSTGRES_PASSWORD: "{{ `{{ .password }}` }}"
        POSTGRES_DB: "{{ `{{ .dbname }}` }}"
        DATABASE_URL: "postgres://{{ `{{ .username }}` }}:{{ `{{ .password | urlquery }}` }}@{{ `{{ .host }}` }}:{{ `{{ .port }}` }}/{{ `{{ .dbname }}` }}?sslmode=verify-full"
        TELEGRAM_BOT_TOKEN: "{{ `{{ .TELEGRAM_BOT_TOKEN }}` }}"
        TELEGRAM_CHAT_ID: "{{ `{{ .TELEGRAM_CHAT_ID }}` }}"
        LLM_API_KEY: "{{ `{{ .LLM_API_KEY }}` }}"
        FINNHUB_API_KEY: "{{ `{{ .FINNHUB_API_KEY }}` }}"
  dataFrom:
    - extract:
        key: ai-stock-pulse-dev-db-secret-20260830074007767700000001
    - extract:
        key: ai-stock-pulse-dev-app-secret