apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: stock-pulse-secretstore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-stock-pulse.labels" . | nindent 4 }}
spec:
  provider:
    fake:
      data:
        - key: POSTGRES_USER
          value: "pulse"
        - key: POSTGRES_PASSWORD
          value: "pulse_local_password"
        - key: POSTGRES_DB
          value: "stock_pulse"
        - key: DATABASE_URL
          value: "postgres://pulse:pulse_local_password@localhost:5432/stock_pulse"
        - key: TELEGRAM_BOT_TOKEN
          value: "aaa"
        - key: TELEGRAM_CHAT_ID
          value: "aaa"
        - key: LLM_API_KEY
          value: "just_a_key"
        - key: FINNHUB_API_KEY
          value: "da2os4pr01qmq2qaro5gda2os4pr01qmq2qaro60"
