apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: stock-pulse-secretstore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-stock-pulse.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1